// <auto-generated />
using System;
using HeatGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatGames.Data.Migrations
{
    [DbContext(typeof(HeatGamesDbContext))]
    [Migration("20260421151150_HeatGamesFinalMig")]
    partial class HeatGamesFinalMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeatGames.Data.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0000-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Rockstar Games",
                            Website = "rockstargames.com"
                        },
                        new
                        {
                            Id = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Valve",
                            Website = "valvesoftware.com"
                        },
                        new
                        {
                            Id = new Guid("cccc0000-cccc-cccc-cccc-cccccccccccc"),
                            Name = "CD Projekt RED",
                            Website = "cdprojektred.com"
                        },
                        new
                        {
                            Id = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Electronic Arts",
                            Website = "ea.com"
                        },
                        new
                        {
                            Id = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Ubisoft",
                            Website = "ubisoft.com"
                        },
                        new
                        {
                            Id = new Guid("ffff0000-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Larian Studios",
                            Website = "larian.com"
                        },
                        new
                        {
                            Id = new Guid("aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "FromSoftware",
                            Website = "fromsoftware.jp"
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg",
                            Description = "An epic tale of life in America's unforgiving heartland.",
                            DeveloperId = new Guid("aaaa0000-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 119.99m,
                            ReleaseDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/271590/capsule_616x353.jpg",
                            Description = "When a young street hustler and a psychopath get entangled with the underworld...",
                            DeveloperId = new Guid("aaaa0000-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2015, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg",
                            Description = "An open-world, action-adventure RPG set in Night City.",
                            DeveloperId = new Guid("cccc0000-cccc-cccc-cccc-cccccccccccc"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/292030/capsule_616x353.jpg",
                            Description = "You are Geralt of Rivia, a mercenary monster slayer.",
                            DeveloperId = new Guid("cccc0000-cccc-cccc-cccc-cccccccccccc"),
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2015, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/730/capsule_616x353.jpg",
                            Description = "The next era of Counter-Strike is here.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2023, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/570/capsule_616x353.jpg",
                            Description = "Every day, millions of players worldwide enter the battle.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2013, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/620/capsule_616x353.jpg",
                            Description = "Innovative gameplay, story, and music with portals.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 19.50m,
                            ReleaseDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Portal 2"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1172470/capsule_616x353.jpg",
                            Description = "Conquer with character in this free-to-play Hero Shooter.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1774580/capsule_616x353.jpg",
                            Description = "The story of Cal Kestis continues.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 139.99m,
                            ReleaseDate = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars Jedi: Survivor"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1426210/capsule_616x353.jpg",
                            Description = "Embark on the craziest journey of your life.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 79.99m,
                            ReleaseDate = new DateTime(2021, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "It Takes Two"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg",
                            Description = "Gather your party and return to the Forgotten Realms.",
                            DeveloperId = new Guid("ffff0000-ffff-ffff-ffff-ffffffffffff"),
                            Price = 119.99m,
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg",
                            Description = "THE NEW FANTASY ACTION RPG. Rise and become an Elden Lord.",
                            DeveloperId = new Guid("aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2022, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/814380/capsule_616x353.jpg",
                            Description = "Take on the role of the 'one-armed wolf', a disgraced and disfigured warrior.",
                            DeveloperId = new Guid("aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = new Guid("0000000e-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/2208920/capsule_616x353.jpg",
                            Description = "Become Eivor, a legendary Viking raider.",
                            DeveloperId = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Price = 119.99m,
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Valhalla"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/359550/capsule_616x353.jpg",
                            Description = "Engage in intense close-quarters combat, tactics, and team play.",
                            DeveloperId = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rainbow Six Siege"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1222670/capsule_616x353.jpg",
                            Description = "Create and control people in a virtual world with no rules.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2014, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sims 4"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/2195250/capsule_616x353.jpg",
                            Description = "The new era of the world's game.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 139.99m,
                            ReleaseDate = new DateTime(2023, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EA SPORTS FC 24"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1328670/capsule_616x353.jpg",
                            Description = "One of the greatest sci-fi franchises of all time.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 119.99m,
                            ReleaseDate = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mass Effect Legendary Edition"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/812140/capsule_616x353.jpg",
                            Description = "Write your own Odyssey in Ancient Greece.",
                            DeveloperId = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Odyssey"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/2369390/capsule_616x353.jpg",
                            Description = "Welcome to Yara, a tropical paradise frozen in time.",
                            DeveloperId = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2021, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Far Cry 6"
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/2239550/capsule_616x353.jpg",
                            Description = "Build a resistance from anyone you meet on the streets of London.",
                            DeveloperId = new Guid("eeee0000-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Price = 89.99m,
                            ReleaseDate = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Watch Dogs: Legion"
                        },
                        new
                        {
                            Id = new Guid("00000016-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/550/capsule_616x353.jpg",
                            Description = "A cooperative first-person zombie survival.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 19.50m,
                            ReleaseDate = new DateTime(2009, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Left 4 Dead 2"
                        },
                        new
                        {
                            Id = new Guid("00000017-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/440/capsule_616x353.jpg",
                            Description = "One of the most popular online action games of all time.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2007, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Fortress 2"
                        },
                        new
                        {
                            Id = new Guid("00000018-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/374320/capsule_616x353.jpg",
                            Description = "The fire fades, and the world falls into ruin.",
                            DeveloperId = new Guid("aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 119.00m,
                            ReleaseDate = new DateTime(2016, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = new Guid("00000019-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://image.api.playstation.com/vulcan/img/rnd/202010/2614/Sy5e8DmeKIJVjlAGraPAJYkT.png",
                            Description = "Face your fears in the city of Yharnam.",
                            DeveloperId = new Guid("aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bloodborne"
                        },
                        new
                        {
                            Id = new Guid("0000001a-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/435150/capsule_616x353.jpg",
                            Description = "Gather your party. Master deep, tactical combat.",
                            DeveloperId = new Guid("ffff0000-ffff-ffff-ffff-ffffffffffff"),
                            Price = 89.99m,
                            ReleaseDate = new DateTime(2017, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Divinity: Original Sin 2"
                        },
                        new
                        {
                            Id = new Guid("0000001b-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/204100/capsule_616x353.jpg",
                            Description = "For Max Payne, the tragedies that took his loved ones are wounds that refuse to heal.",
                            DeveloperId = new Guid("aaaa0000-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2012, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Max Payne 3"
                        },
                        new
                        {
                            Id = new Guid("0000001c-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/12200/capsule_616x353.jpg",
                            Description = "Experience high school as the troubled teenager Jimmy Hopkins.",
                            DeveloperId = new Guid("aaaa0000-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2008, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bully: Scholarship Edition"
                        },
                        new
                        {
                            Id = new Guid("0000001d-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/2138330/capsule_616x353.jpg",
                            Description = "A spy-thriller expansion for Cyberpunk 2077.",
                            DeveloperId = new Guid("cccc0000-cccc-cccc-cccc-cccccccccccc"),
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077: Phantom Liberty"
                        },
                        new
                        {
                            Id = new Guid("0000001e-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/367520/capsule_616x353.jpg",
                            Description = "Explore vast, interconnected worlds in this award-winning indie game.",
                            DeveloperId = new Guid("ffff0000-ffff-ffff-ffff-ffffffffffff"),
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = new Guid("0000001f-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/413150/capsule_616x353.jpg",
                            Description = "You've inherited your grandfather's old farm plot. It's time to begin a new life.",
                            DeveloperId = new Guid("dddd0000-dddd-dddd-dddd-dddddddddddd"),
                            Price = 27.99m,
                            ReleaseDate = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = new Guid("00000020-0000-0000-0000-000000000000"),
                            CoverImageUrl = "https://cdn.akamai.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg",
                            Description = "Hack and slash your way out of the Underworld in this rogue-like dungeon crawler.",
                            DeveloperId = new Guid("bbbb0000-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades"
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("00000001-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000001-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000002-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000003-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000003-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000005-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000006-0000-0000-0000-000000000000"),
                            GenreId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000006-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000007-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000008-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000009-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000009-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000b-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000b-0000-0000-0000-000000000000"),
                            GenreId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000c-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000c-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000d-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000d-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000e-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000e-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000f-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000000f-0000-0000-0000-000000000000"),
                            GenreId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000010-0000-0000-0000-000000000000"),
                            GenreId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000011-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000012-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000012-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000013-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000013-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000014-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000014-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000015-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000015-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000016-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000017-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000018-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000018-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000019-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000019-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001a-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001a-0000-0000-0000-000000000000"),
                            GenreId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001b-0000-0000-0000-000000000000"),
                            GenreId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001b-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001c-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001c-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001d-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001d-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001e-0000-0000-0000-000000000000"),
                            GenreId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001e-0000-0000-0000-000000000000"),
                            GenreId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001f-0000-0000-0000-000000000000"),
                            GenreId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("0000001f-0000-0000-0000-000000000000"),
                            GenreId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000020-0000-0000-0000-000000000000"),
                            GenreId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            GameId = new Guid("00000020-0000-0000-0000-000000000000"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("00000001-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000001-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000001-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000002-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000002-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000002-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000003-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000003-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000003-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000004-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("00000005-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000006-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000007-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000007-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("00000008-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000008-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000008-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000008-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("00000009-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000009-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000009-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000000a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("0000000b-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000b-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000000d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000000e-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000e-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000e-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000000f-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000000f-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000000f-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000010-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000011-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000011-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000011-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000012-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000012-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000012-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000013-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000013-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000013-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000014-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000014-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000014-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000015-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000015-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000015-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000016-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000017-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000018-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000018-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000018-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("00000019-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000001a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000001a-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("0000001b-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001b-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000001c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000001c-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000001d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("0000001d-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("33333333-4444-5555-6666-777777777777")
                        },
                        new
                        {
                            GameId = new Guid("0000001e-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001e-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("0000001f-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("0000001f-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        },
                        new
                        {
                            GameId = new Guid("00000020-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("11111111-2222-3333-4444-555555555555")
                        },
                        new
                        {
                            GameId = new Guid("00000020-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("22222222-3333-4444-5555-666666666666")
                        },
                        new
                        {
                            GameId = new Guid("00000020-0000-0000-0000-000000000000"),
                            PlatformId = new Guid("44444444-5555-6666-7777-888888888888")
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Indie"
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.LibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HeatGames.Data.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            Name = "PC (Windows)"
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            Name = "Xbox Series X/S"
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            Name = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("HeatGames.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HeatGames.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HeatGames.Data.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeatGames.Data.Models.Game", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("HeatGames.Data.Models.GameGenre", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("HeatGames.Data.Models.GamePlatform", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("HeatGames.Data.Models.LibraryItem", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.User", "User")
                        .WithMany("LibraryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Order", b =>
                {
                    b.HasOne("HeatGames.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeatGames.Data.Models.OrderItem", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Review", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Wishlist", b =>
                {
                    b.HasOne("HeatGames.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HeatGames.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HeatGames.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeatGames.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HeatGames.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeatGames.Data.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HeatGames.Data.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("HeatGames.Data.Models.User", b =>
                {
                    b.Navigation("LibraryItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
